default: &default
  adapter: postgresql
  encoding: unicode
  pool: 1

development:
  <<: *default
  database: forum_reader_development

test:
  <<: *default
  database: forum_reader_test

production:
  <<: *default
  database: forum_reader_production
